---
title: "DemographicData"
author: "Junhong Duan"
date: "2024-11-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install.packages("tidycensus")
remotes::install_github("mikejohnson51/climateR")

```

```{r}
library(tidycensus)
library(dplyr)
library(ggplot2)
library(tidyr)
library(sf)

LAcity_shapefile <- st_read("../Data/Los_Angeles_City_shapefile_2018.shp")
#str(LAcity_shapefile)
CA_census_tract_shp <- st_read('../Data/CA_census tract_2018_boundary_shapefile/tl_2018_06_tract/tl_2018_06_tract.shp')
#str(CA_census_tract_shp)
CA_census_tract_shp$GEOID_numeric <- as.numeric(CA_census_tract_shp$GEOID)
#head(CA_census_tract_shp$GEOID_numeric)
if (st_crs(CA_census_tract_shp) != st_crs(LAcity_shapefile)) {
  LAcity_shapefile <- st_transform(LAcity_shapefile, st_crs(CA_census_tract_shp))
}
LA_census_tracts <- st_intersection(CA_census_tract_shp, LAcity_shapefile)
# print(LA_census_tracts)
plot(st_geometry(LA_census_tracts))
```

```{r}
# 59c822f1e8302f7e57bbdd6d0cf1fd7649de1f0e
census_api_key("59c822f1e8302f7e57bbdd6d0cf1fd7649de1f0e", install = TRUE, overwrite=TRUE)

base_variables <- c(
  "S0101_C01_001E", "S0101_C02_001E", "S0101_C03_001E",
  "S0101_C01_002E", "S0101_C01_003E", "S0101_C01_004E",
  "S0101_C01_005E", "S0101_C01_006E", "S0101_C01_007E",
  "S0101_C01_008E", "S0101_C01_009E", "S0101_C01_010E",
  "S0101_C01_011E", "S0101_C01_012E", "S0101_C01_013E",
  "S0101_C01_014E", "S0101_C01_015E", "S0101_C01_016E",
  "S0101_C01_017E", "S0101_C01_018E", "S0101_C01_019E"
)

extra_variable <- "S0101_C05_001E"
all_data <- list()

for (year in 2010:2019) {
  S0101_variables <- if (year <= 2016) {
    base_variables
  } else {
    c(base_variables, extra_variable)  # 添加额外变量
  }
  
  S0101_table <- get_acs(
    geography = "tract",
    variables = S0101_variables,
    year = year,
    state = "CA",
    county = "Los Angeles",
    survey = "acs5",
    output = "wide"
  )
  
  data_clean <- S0101_table %>%
    mutate(
      year = year,
      population = S0101_C01_001E,
      male = ifelse(
       year >= 2010 & year <= 2016, 
        S0101_C02_001E, S0101_C03_001E
      ),
      female = ifelse(
       year >= 2010 & year <= 2016, 
        S0101_C03_001E, S0101_C05_001E
      ),
      male_ratio = male/population,
      norm_age_0_19 = ifelse(
        year >= 2010 & year <= 2016, 
        S0101_C01_002E + S0101_C01_003E + S0101_C01_004E + S0101_C01_005E, 
        (S0101_C01_002E + S0101_C01_003E + S0101_C01_004E + S0101_C01_005E)/population*100
      ),
      norm_age_20_69 = ifelse(
        year >= 2010 & year <= 2016, 
        S0101_C01_006E + S0101_C01_007E + S0101_C01_008E + S0101_C01_009E + S0101_C01_010E + S0101_C01_011E +
           S0101_C01_012E + S0101_C01_013E + S0101_C01_014E + S0101_C01_015E, 
        (S0101_C01_006E + S0101_C01_007E + S0101_C01_008E + S0101_C01_009E + S0101_C01_010E + S0101_C01_011E +
           S0101_C01_012E + S0101_C01_013E + S0101_C01_014E + S0101_C01_015E)/population*100
      ),
      norm_age_70_plus = ifelse(
        year >= 2010 & year <= 2016, 
        S0101_C01_016E + S0101_C01_017E + S0101_C01_018E + S0101_C01_019E, 
        (S0101_C01_016E + S0101_C01_017E + S0101_C01_018E + S0101_C01_019E)/population*100
      )
    ) %>%
    select(GEOID, NAME, year, population, male, female, male_ratio, norm_age_0_19, norm_age_20_69, norm_age_70_plus)
  
  
  
  # output_file <- paste0("../Data/Demographic_Nov16/S0101_convertedByGroups/LA_Census_Tract_Data_", year, ".csv")
  # write.csv(data_clean, output_file, row.names = FALSE)
  data_clean <- left_join(LA_census_tracts, data_clean, by = c("GEOID" = "GEOID"))
  all_data[[as.character(year)]] <- data_clean
  
  
  
  # 打印状态信息
  message("Saved data for year: ", year)
}

combined_data <- bind_rows(all_data)
combined_data <- combined_data %>% st_drop_geometry()%>%
  select(GEOID, year, population, male, female, male_ratio, age_0_19, age_20_69, age_70_plus)

write.csv(combined_data, "../Data/Demographic_Nov16/all_year_pop_gender_race_maleRatio.csv", row.names = FALSE)


```


```{r}
library(purrr)
race_codes <- c("A", "B", "C", "D", "E", "F", "G")
race_names <- c("white", "black", "indian", "asian", "island", "other", "multi")
all_year_race_data <- list()
for (year in 2010:2019) {
  yearly_race_data <- list()
  
  # 遍历种族代码和名称
  for (i in seq_along(race_codes)) {
    race_code <- race_codes[i]
    race_name <- race_names[i]
    race_var <- paste0("B01001", race_code, "_001E")
    
    # 使用get_acs获取数据
    race_table <- get_acs(
      geography = "tract",
      variables = race_var,
      year = year,
      state = "CA",
      county = "Los Angeles",
      survey = "acs5",
      output = "wide"
    )
    
    # 合并数据
    yearly_data <- left_join(LA_census_tracts, race_table, by = c("GEOID" = "GEOID"))
    yearly_data <- yearly_data %>%
      mutate(year = year,
             !!race_name := !!sym(race_var)) %>%
      select(GEOID, year, !!sym(race_name))
    
    yearly_race_data[[race_name]] <- st_drop_geometry(yearly_data)
  }

  combined_yearly_data <- reduce(yearly_race_data, function(x, y) full_join(x, y, by = c("GEOID", "year")))
  # Simpson's index
  combined_yearly_data <- combined_yearly_data %>%
    rowwise() %>%
    mutate(
      total_population = sum(c_across(white:multi), na.rm = TRUE),
      race_diversity = 1 - sum((c_across(white:multi) / total_population)^2, na.rm = TRUE)
    ) %>%
    ungroup()
  
  all_year_race_data[[as.character(year)]] <- combined_yearly_data
}
combined_all_year_race_data <- bind_rows(all_year_race_data)
print(combined_all_year_race_data)
write.csv(combined_all_year_race_data, "../Data/Demographic_Nov16/all_year_race.csv", row.names = FALSE)
```


```{r}

years <- 2010:2019
all_data <- list()

for (year in years) {
  file_name <- paste0("../Data/Demographic_Nov16/S0101_convertedByGroups/LA_Census_Tract_Data_", year, ".csv")
  yearly_data <- read.csv(file_name)
  yearly_data <- left_join(LA_census_tracts, yearly_data, by = c("GEOID_numeric" = "GEOID"))
  yearly_data <- yearly_data %>%
    mutate(male_ratio = male/population,
           ) %>%
    select(GEOID, year, male_ratio)  # 只保留需要的列
  all_data[[as.character(year)]] <- yearly_data
 
  map <- ggplot(data = yearly_data) +
    geom_sf(aes(fill = male_ratio), color = NA) +  # 使用男性比例填充
    scale_fill_viridis_c(
      name = "Male Ratio",
      na.value = "grey50",
      limits = c(0, 1)  # 固定颜色范围为 0-1
    ) +
    labs(
      title = paste("Male Ratio in Los Angeles City Census Tracts (", year, ")", sep = ""),
      caption = "Data Source: ACS 5-year estimates"
    ) +
    theme_minimal()
  plot(map)
  ggsave(
    filename = paste0("../Data/Demographic_Nov16/img/LA_Census_Tracts_Male_Ratio_", year, ".png"),
    plot = map,
    width = 8,
    height = 6
 )
 cat("Map for year", year, "saved as LA_Census_Tracts_Male_Ratio_", year, ".png\n", sep = "")
  
}
combined_data <- bind_rows(all_data)
combined_data <- combined_data %>% st_drop_geometry()

write.csv(combined_data, "../Data/Demographic_Nov16/all_year_maleRatio.csv", row.names = FALSE)

yearly_avg <- combined_data %>%
  group_by(year) %>%
  summarize(avg_sex_ratio = mean(male_ratio, na.rm = TRUE))

tract_lines <- ggplot() +
  geom_line(data = combined_data, aes(x = year, y = male_ratio, group = GEOID), 
            alpha = 0.1, color = "blue") +
  geom_line(data = yearly_avg, aes(x = year, y = avg_sex_ratio), 
            color = "red", linewidth = 1, linetype = "dashed") +
  labs(
    title = "Sex Ratio Trends for Census Tracts in Los Angeles County (2010-2019)",
    x = "Year",
    y = "Male Ratio (Male / population)"
  ) +
  scale_y_continuous(limits = c(0, 1)) +
  scale_x_continuous(
    breaks = 2010:2019,  
    labels = 2010:2019  
  ) +
  theme_minimal()
print(tract_lines)
```


```{r} 
# percent families below poverty line
belowPovertylevel_var <- "S1702_C02_001E"
all_year_belowPovertylevel <- list()
for (year in 2010:2019) {
  S1702_table <- get_acs(
      geography = "tract",
      variables = belowPovertylevel_var,
      year = year,
      state = "CA",
      county = "Los Angeles",
      survey = "acs5",
      output = "wide"
    )
  yearly_data <- left_join(LA_census_tracts, S1702_table, by = c("GEOID" = "GEOID"))
  yearly_data <- yearly_data %>%
    mutate(year = year,
           lowerThanPovertyLine = S1702_C02_001E) %>%
    select(GEOID, year, lowerThanPovertyLine)
  all_year_belowPovertylevel[[as.character(year)]] <- yearly_data
  
  map <- ggplot(data = yearly_data) +
    geom_sf(aes(fill = lowerThanPovertyLine), color = NA) + 
    scale_fill_viridis_c(
      name = "Percent of Families Below Poverty Line",
      na.value = "grey50",
      limits = c(0, 100)  # 固定颜色范围为 0-1
    ) +
    labs(
      title = paste("Percent of Families Below Poverty Line in Los Angeles City Census Tracts (", year, ")", sep = ""),
      caption = "Data Source: ACS 5-year estimates"
    ) +
    theme_minimal()
  plot(map)
  ggsave(
    filename = paste0("../Data/Demographic_Nov16/img/LA_Census_Tracts_lowerthanpovertyline_", year, ".png"),
    plot = map,
    width = 8,
    height = 6
  )
 cat("Map for year", year, "saved as LA_Census_Tracts_lowerthanpovertyline_", year, ".png\n", sep = "")
}
combined_all_year_belowPovertylevel <- bind_rows(all_year_belowPovertylevel)
combined_all_year_belowPovertylevel <- combined_all_year_belowPovertylevel %>% st_drop_geometry()

write.csv(combined_all_year_belowPovertylevel, "../Data/Demographic_Nov16/all_year_belowPovertylevel.csv", row.names = FALSE)
print(combined_all_year_belowPovertylevel)

yearly_belowPovertylevel_avg <- combined_all_year_belowPovertylevel %>%
  group_by(year) %>%
  summarize(avg_percLowerthanPoverty = mean(lowerThanPovertyLine, na.rm = TRUE))

tract_lines <- ggplot() +
  geom_line(data = combined_all_year_belowPovertylevel, aes(x = year, y = lowerThanPovertyLine, group = GEOID),
            alpha = 0.1, color = "blue") +
  geom_line(data = yearly_belowPovertylevel_avg, aes(x = year, y = avg_percLowerthanPoverty),
            color = "red", linewidth = 1, linetype = "dashed") +
  labs(
    title = "Change in Percent of Families Below Poverty Line (2010-2019)",
    x = "Year",
    y = "Percent Families Below Poverty Line"
  ) +
  #scale_y_continuous(limits = c(0, 1)) +
  #scale_x_continuous(
  #  breaks = 2010:2019,  
  #  labels = 2010:2019  
  #) +
  theme_minimal()
print(tract_lines)

```

```{r}
# mean and median income
# percent families below poverty line
Income_var <- c("S1901_C01_012E", "S1901_C01_013E")
all_year_income <- list()
for (year in 2010:2019) {
  S1901_table <- get_acs(
      geography = "tract",
      variables = Income_var,
      year = year,
      state = "CA",
      county = "Los Angeles",
      survey = "acs5",
      output = "wide"
    )
  yearly_data <- left_join(LA_census_tracts, S1901_table, by = c("GEOID" = "GEOID"))
  yearly_data <- yearly_data %>%
    mutate(year = year,
           median_income = S1901_C01_012E,
           mean_income = S1901_C01_013E) %>%
    select(GEOID, year, median_income, mean_income)
  all_year_income[[as.character(year)]] <- yearly_data
  
  write.csv(combined_all_year_income, paste("../Data/Demographic_Nov16/Year",year,"_income.csv"), row.names = FALSE)
  
  Median_map <- ggplot(data = yearly_data) +
    geom_sf(aes(fill = median_income), color = NA) + 
    scale_fill_viridis_c(
      name = "Household Median Income Line",
      na.value = "grey50"#,
      #limits = c(0, 100)  # 固定颜色范围为 0-1
    ) +
    labs(
      title = paste("Household Median Income Line in Los Angeles City Census Tracts (", year, ")", sep = ""),
      caption = "Data Source: ACS 5-year estimates"
    ) +
    theme_minimal()
  plot(Median_map)
  ggsave(
    filename = paste0("../Data/Demographic_Nov16/img/LA_Census_Tracts_MedianIncome_", year, ".png"),
    plot = Median_map,
    width = 8,
    height = 6
  )
  cat("Map for year", year, "saved as LA_Census_Tracts_MedianIncome_", year, ".png\n", sep = "")
 
  Mean_map <- ggplot(data = yearly_data) +
    geom_sf(aes(fill = mean_income), color = NA) + 
    scale_fill_viridis_c(
      name = "Household Mean Income Line",
      na.value = "grey50"#,
      #limits = c(0, 100)  # 固定颜色范围为 0-1
    ) +
    labs(
      title = paste("Household Mean Income Line in Los Angeles City Census Tracts (", year, ")", sep = ""),
      caption = "Data Source: ACS 5-year estimates"
    ) +
    theme_minimal()
  plot(Mean_map)
  ggsave(
    filename = paste0("../Data/Demographic_Nov16/img/LA_Census_Tracts_MeanIncome_", year, ".png"),
    plot = Mean_map,
    width = 8,
    height = 6
  )
 cat("Map for year", year, "saved as LA_Census_Tracts_MeanIncome_", year, ".png\n", sep = "")
 
}
combined_all_year_income <- bind_rows(all_year_income)
combined_all_year_income <- combined_all_year_income %>% st_drop_geometry()

write.csv(combined_all_year_income, "../Data/Demographic_Nov16/all_year_income.csv", row.names = FALSE)
print(combined_all_year_income)

yearly_income_avg <- combined_all_year_income %>%
  group_by(year) %>%
  summarize(
    avg_mean_income = mean(mean_income, na.rm = TRUE),
    avg_median_income = mean(median_income, na.rm = TRUE)
  )

mean_income_tract_lines <- ggplot() +
  geom_line(data = combined_all_year_income, aes(x = year, y = mean_income, group = GEOID),
            alpha = 0.1, color = "blue") +
  geom_line(data = yearly_income_avg, aes(x = year, y = avg_mean_income),
            color = "red", linewidth = 1, linetype = "dashed") +
  labs(
    title = "Change in Mean Income Line (2010-2019)",
    x = "Year",
    y = "Household Mean Income"
  ) +
  #scale_y_continuous(limits = c(0, 1)) +
  scale_x_continuous(
    breaks = 2010:2019,  
    labels = 2010:2019  
  ) +
  theme_minimal()

median_income_tract_lines <- ggplot() +
  geom_line(data = combined_all_year_income, aes(x = year, y = median_income, group = GEOID),
            alpha = 0.1, color = "blue") +
  geom_line(data = yearly_income_avg, aes(x = year, y = avg_mean_income),
            color = "red", linewidth = 1, linetype = "dashed") +
  labs(
    title = "Change in Median Income Line (2010-2019)",
    x = "Year",
    y = "Household Median Income"
  ) +
  #scale_y_continuous(limits = c(0, 1)) +
  scale_x_continuous(
    breaks = 2010:2019,  
    labels = 2010:2019  
  ) +
  theme_minimal()
print(mean_income_tract_lines)
print(median_income_tract_lines)


```


```{r}
# unempolyment rate

#2010 - 2012: DP03_0005PE
#2013 - 2019: DP03_0009PE
# 
all_year_unemployment <- list()
for (year in 2010:2019) {
  
  if (year >= 2010 && year <= 2012) {
    unemployment_var <- "DP03_0005PE"
    } else if (year >= 2013) {
    unemployment_var <- "DP03_0009PE"
    }
  # ------------------------ 从本地下载文件导入变量 ------------------------
  file_path <- paste0("../Data/DP03_unemployment/ACSDP5Y", year, ".DP03-Data.csv")
  local_data <- read.csv(file_path)
  local_data$GEOID <- sub(".*US", "", local_data$GEO_ID)
  DP03_table <- local_data %>%
    slice(-1) %>%
    mutate(
      unemploymentRate = !!sym(unemployment_var)
      )%>%
    select(GEOID, unemploymentRate)
  # ------------------------ 从本地下载文件导入变量 END ------------------------
  
  # DP03_table <- get_acs(
  #     geography = "tract",
  #     variables = unemployment_var,
  #     year = year,
  #     state = "CA",
  #     county = "Los Angeles",
  #     survey = "acs5",
  #     output = "wide"
  #   )
  yearly_data <- left_join(LA_census_tracts, DP03_table, by = "GEOID")
  yearly_data <- yearly_data %>%
    mutate(
      year = year,
      unemployment_rate = as.numeric(unemploymentRate)#,
      #quintile = cut(
      #  unemployment_rate,
      #  breaks = quantile(unemployment_rate, probs = seq(0, 1, 0.2), na.rm = TRUE),
      #  labels = c("Lowest", "Low", "Medium", "High", "Highest"),
      #  include.lowest = TRUE
      #)
    ) %>%
    select(GEOID, year, unemployment_rate)#, quintile)
  
  all_year_unemployment[[as.character(year)]] <- yearly_data
  
  unemployment_map <- ggplot(data = yearly_data) +
    geom_sf(aes(fill = unemployment_rate), color = NA) + 
    scale_fill_viridis_c(#scale_fill_viridis_d
      name = "Unemployment Rate Line",
      na.value = "grey50",
      limits = c(0, 30)  # 固定颜色范围为 0-1 ############### continuous map
    ) +
    labs(
      title = paste("Unemployment Rate Line in Los Angeles City Census Tracts (", year, ")", sep = ""),
      caption = "Data Source: ACS 5-year estimates"
    ) +
    theme_minimal()
  plot(unemployment_map)
  ggsave(
    filename = paste0("../Data/Demographic_Nov16/img/LA_Census_Tracts_unemployment_", year, ".png"),
    plot = unemployment_map,
    width = 8,
    height = 6
  )
 cat("Map for year", year, "saved as LA_Census_Tracts_unemployment_", year, ".png\n", sep = "")
}
combined_all_year_unemployment <- bind_rows(all_year_unemployment)
combined_all_year_unemployment <- combined_all_year_unemployment %>% st_drop_geometry()

write.csv(combined_all_year_unemployment, "../Data/Demographic_Nov16/all_year_unemployment.csv", row.names = FALSE)
print(combined_all_year_unemployment)

yearly_unemployment_avg <- combined_all_year_unemployment %>%
  group_by(year) %>%
  summarize(avg_unemployment = mean(unemployment_rate, na.rm = TRUE))

tract_lines <- ggplot() +
  geom_line(data = combined_all_year_unemployment, aes(x = year, y = unemployment_rate, group = GEOID),
            alpha = 0.1, color = "blue") +
  geom_line(data = yearly_unemployment_avg, aes(x = year, y = avg_unemployment),
            color = "red", linewidth = 1, linetype = "dashed") +
  labs(
    title = "Change in Unemployment Rate Line (2010-2019)",
    x = "Year",
    y = "Unemployment Rate Line"
  ) +
  scale_y_continuous(limits = c(0,30)) +
  scale_x_continuous(
    breaks = 2010:2019,  
    labels = 2010:2019  
  ) +
  theme_minimal()
print(tract_lines)


```

```{r} 
# housing unit vacancy r
HHvacancy_var <- c("B25002_001E","B25002_003E")
all_year_HHvacancy <- list()
for (year in 2010:2019) {
  B25002_table <- get_acs(
      geography = "tract",
      variables = HHvacancy_var,
      year = year,
      state = "CA",
      county = "Los Angeles",
      survey = "acs5",
      output = "wide"
    )
  yearly_data <- left_join(LA_census_tracts, B25002_table, by = c("GEOID" = "GEOID"))
  yearly_data <- yearly_data %>%
    mutate(year = year,
           vacancy_perc = B25002_003E/B25002_001E) %>%
    select(GEOID, year, vacancy_perc)
  all_year_HHvacancy[[as.character(year)]] <- yearly_data
  
  map <- ggplot(data = yearly_data) +
    geom_sf(aes(fill = vacancy_perc), color = NA) + 
    scale_fill_viridis_c(
      name = "Housing Unit Vacancy Rate Line",
      na.value = "grey50",
      limits = c(0, 0.25) 
    ) +
    labs(
      title = paste("Housing Unit Vacancy Line in Los Angeles City Census Tracts (", year, ")", sep = ""),
      caption = "Data Source: ACS 5-year estimates"
    ) +
    theme_minimal()
  plot(map)
  ggsave(
    filename = paste0("../Data/Demographic_Nov16/img/LA_Census_Tracts_HHVacancyRate_", year, ".png"),
    plot = map,
    width = 8,
    height = 6
  )
 cat("Map for year", year, "saved as LA_Census_Tracts_HHVacancyRate_", year, ".png\n", sep = "")
}
combined_all_year_HHvacancy <- bind_rows(all_year_HHvacancy)
combined_all_year_HHvacancy <- combined_all_year_HHvacancy %>% st_drop_geometry()

write.csv(combined_all_year_HHvacancy, "../Data/Demographic_Nov16/all_year_HHvacancy.csv", row.names = FALSE)
print(combined_all_year_HHvacancy)

yearly_HHvacancy_avg <- combined_all_year_HHvacancy %>%
  group_by(year) %>%
  summarize(avg_HHvacancyy = mean(vacancy_perc, na.rm = TRUE))

tract_lines <- ggplot() +
  geom_line(data = combined_all_year_HHvacancy, aes(x = year, y = vacancy_perc, group = GEOID),
            alpha = 0.1, color = "blue") +
  geom_line(data = yearly_HHvacancy_avg, aes(x = year, y = avg_HHvacancyy),
            color = "red", linewidth = 1, linetype = "dashed") +
  labs(
    title = "Change in Household Vacancy Rate Line (2010-2019)",
    x = "Year",
    y = "Household Vacancy Rate Line"
  ) +
  scale_y_continuous(limits = c(0, 0.25)) +
  #scale_x_continuous(
  #  breaks = 2010:2019,  
  #  labels = 2010:2019  
  #) +
  theme_minimal()
print(tract_lines)

```


```{r}
# housing unit occupancy percentage
# renter-occupied housing units
all_year_housingUnits <- list()

# 循环遍历年份
for (year in 2010:2019) {
  print(year)
  
  # 根据年份选择变量
  if (year < 2019) {
    housingUnits_var <- c("DP04_0002PE", "DP04_0001E", "DP04_0002E", "DP04_0046E", "DP04_0046E")
  } else {
    housingUnits_var <- c("DP04_0002PE", "DP04_0001E", "DP04_0002E", "DP04_0045E", "DP04_0047E")
  }
  
  # 提取数据
  DP04_table <- get_acs(
    geography = "tract",
    variables = housingUnits_var,
    year = year,
    state = "CA",
    county = "Los Angeles",
    survey = "acs5",
    output = "wide"
  )
  
  # 合并数据并处理
  yearly_data <- left_join(LA_census_tracts, DP04_table, by = c("GEOID" = "GEOID"))
  yearly_data <- yearly_data %>%
    mutate(
      year = year,
      HU_occupied_renter = ifelse(year < 2019, DP04_0046E, DP04_0047E),
      HU_occupied_perc = DP04_0002PE,
      rent_rate = HU_occupied_renter/DP04_0001E
    ) %>%
    select(GEOID, year, HU_occupied_perc, rent_rate)
  
  # 保存到列表中
  all_year_housingUnits[[as.character(year)]] <- yearly_data
}
combined_all_year_housingUnits <- bind_rows(all_year_housingUnits)
combined_all_year_housingUnits <- combined_all_year_housingUnits %>% st_drop_geometry()

write.csv(combined_all_year_housingUnits, "../Data/Demographic_Nov16/all_year_HousingUnit.csv", row.names = FALSE)
print(combined_all_year_housingUnits)

```


```{r}
# year built - ACS 2022 (latest)
YearBuilt_var <- c("S2504_C01_010E","S2504_C01_011E","S2504_C01_012E","S2504_C01_013E","S2504_C01_014E","S2504_C01_015E")

yearBuilt_table <- get_acs(
    geography = "tract",
    variables = YearBuilt_var,
    year = 2019,
    state = "CA",
    county = "Los Angeles",
    survey = "acs5",
    output = "wide"
  )
YB_data <- left_join(LA_census_tracts, yearBuilt_table, by = c("GEOID" = "GEOID"))
YB_data <- YB_data %>%
  mutate(
         YBealierThan1939 = S2504_C01_015E,
         YB1940_1959 = S2504_C01_014E,
         YB1960_1979 = S2504_C01_013E,
         YB1980_1999 = S2504_C01_012E,
         YB2000_2009 = S2504_C01_011E,
         YB2010_2019 = S2504_C01_010E) %>%
  select(GEOID, YBealierThan1939, YB1940_1959, YB1960_1979, YB1980_1999, YB2000_2009, YB2010_2019)%>%
  mutate(
    total = YBealierThan1939 + YB1940_1959 + YB1960_1979 + YB1980_1999 + YB2000_2009 + YB2010_2019,
    YB_before_1979_pct = (YBealierThan1939 + YB1940_1959 + YB1960_1979)/ total * 100,
    YB_1980_2019_pct = (YB1980_1999+YB2000_2009+YB2010_2019) / total * 100,
    dummy_BY_thredhold50perc = if_else(YB_1980_2019_pct > 50, 1, 0)
  ) %>%
  select(GEOID, YB_before_1979_pct, YB_1980_2019_pct, dummy_BY_thredhold50perc) %>%
  st_drop_geometry()
YB_data <- YB_data %>% st_drop_geometry()
write.csv(YB_data, "../Data/Demographic_Nov16/year2019_YearBuilt.csv", row.names = FALSE)
```

```{r}
# median year structure built
MedianYearBuilt_var <- c("B25035_001E")
all_year_MYB <- list()
for (year in 2010:2019){
  MedianyearBuilt_table <- get_acs(
      geography = "tract",
      variables = MedianYearBuilt_var,
      year = year,
      state = "CA",
      county = "Los Angeles",
      survey = "acs5",
      output = "wide"
    )
  
  MYB_yearly_data <- left_join(LA_census_tracts, MedianyearBuilt_table, by = c("GEOID" = "GEOID"))
  MYB_yearly_data <- MYB_yearly_data %>%
  mutate(
    year = year,
    B25035_001E = ifelse(B25035_001E == 0, 1939, B25035_001E),
    B25035_001E = ifelse(grepl("-", B25035_001E), NA, B25035_001E),
    MYB_ages = ifelse(is.na(B25035_001E), NA, year - B25035_001E)
  ) %>%
  select(GEOID, year, MYB_ages)
  all_year_MYB[[as.character(year)]] <- MYB_yearly_data
}
combined_MYB_data <- bind_rows(all_year_MYB)
combined_MYB_data <- combined_MYB_data %>% st_drop_geometry()

write.csv(combined_MYB_data, "../Data/Demographic_Nov16/all_year_MYB.csv", row.names = FALSE)
print(combined_MYB_data)
```

```{r}
# 2010-2014: S1501_C01_002E
# 2015 +: 1-S1501_C01_014E
all_year_education <- list()
for (year in 2010:2019) {
  
  if (year >= 2010 && year <= 2014) {
    education_var <- "S1501_C01_002E"
    } else if (year >= 2015) {
    education_var <- "S1501_C01_014E"
    }
  
  S501_table <- get_acs(
      geography = "tract",
      variables = education_var,
      year = year,
      state = "CA",
      county = "Los Angeles",
      survey = "acs5",
      output = "wide"
    )
  S501_table <- S501_table %>%
    mutate(
      NoHighSchoolPerc = !!sym(education_var)
      )
  
  yearly_data <- left_join(LA_census_tracts, S501_table, by = c("GEOID" = "GEOID"))
  
  if(year >= 2015){
    yearly_data <- yearly_data %>%
    mutate(
      LessThanHighSchoolPerc = 1 - NoHighSchoolPerc,
      year = year
    ) %>%
    select(GEOID, year, LessThanHighSchoolPerc)
  }else if(year < 2015){
    yearly_data <- yearly_data %>%
    mutate(
      LessThanHighSchoolPerc = NoHighSchoolPerc,
      year = year
    ) %>%
    select(GEOID, year, LessThanHighSchoolPerc)
  }
  
  all_year_education[[as.character(year)]] <- yearly_data
  
  map1 <- ggplot(data = yearly_data) +
    geom_sf(aes(fill = LessThanHighSchoolPerc), color = NA) + 
    scale_fill_viridis_c(
      name = "Percentage of people Less Than High School Graduate Line",
      na.value = "grey50",
      limits = c(0, 100) 
    ) +
    labs(
      title = paste("Percentage of people graduated from High School Line in Los Angeles City Census Tracts (", year, ")", sep = ""),
      caption = "Data Source: ACS 5-year estimates"
    ) +
    theme_minimal()
  plot(map1)
  ggsave(
    filename = paste0("../Data/Demographic_Nov16/img/LA_Census_Tracts_education", year, ".png"),
    plot = map,
    width = 8,
    height = 6
  )
 cat("Map for year", year, "saved as LA_Census_Tracts_education", year, ".png\n", sep = "")
}

combined_all_year_education <- bind_rows(all_year_education)
combined_all_year_education <- combined_all_year_education %>% st_drop_geometry()

write.csv(combined_all_year_education, "../Data/Demographic_Nov16/all_year_education.csv", row.names = FALSE)
print(combined_all_year_education)

yearly_education_avg <- combined_all_year_education %>%
  group_by(year) %>%
  summarize(avg_education = mean(LessThanHighSchoolPerc, na.rm = TRUE))

tract_lines <- ggplot() +
  geom_line(data = combined_all_year_education, aes(x = year, y = LessThanHighSchoolPerc, group = GEOID),
            alpha = 0.1, color = "blue") +
  geom_line(data = yearly_education_avg, aes(x = year, y = avg_education),
            color = "red", linewidth = 1, linetype = "dashed") +
  labs(
    title = "Change in Percentage of people less than high schoool graduate Line (2010-2019)",
    x = "Year",
    y = "Percentage of people less than high schoool graduate Line"
  ) +
  scale_y_continuous(limits = c(0, 100)) #+
  #scale_x_continuous(
  #  breaks = 2010:2019,  
  #  labels = 2010:2019  
  #) +
  theme_minimal()
print(tract_lines)

```

```{r}
# percent families below poverty line
PercFamiliesBelowPovertyline_var <- c("S1702_C02_001E") #All families!!Percent below poverty level!!Estimate!!Families
all_year_PercFamiliesBelowPovertyline <- list()
for (year in 2010:2019) {
  S1702_table <- get_acs(
      geography = "tract",
      variables = PercFamiliesBelowPovertyline_var,
      year = year,
      state = "CA",
      county = "Los Angeles",
      survey = "acs5",
      output = "wide"
    )
  yearly_data <- left_join(LA_census_tracts, S1702_table, by = c("GEOID" = "GEOID"))
  yearly_data <- yearly_data %>%
    mutate(year = year,
           PercFamiliesBelowPovertyline = S1702_C02_001E) %>%
    select(GEOID, year, PercFamiliesBelowPovertyline)
  all_year_PercFamiliesBelowPovertyline[[as.character(year)]] <- yearly_data
  
  map <- ggplot(data = yearly_data) +
    geom_sf(aes(fill = PercFamiliesBelowPovertyline), color = NA) + 
    scale_fill_viridis_c(
      name = "Percentage of Families Below Poverty Line",
      na.value = "grey50",
      limits = c(0, 100) 
    ) +
    labs(
      title = paste("Percentage of Families Below Poverty Line in Los Angeles City Census Tracts (", year, ")", sep = ""),
      caption = "Data Source: ACS 5-year estimates"
    ) +
    theme_minimal()
  plot(map)
  ggsave(
    filename = paste0("../Data/Demographic_Nov16/img/LA_Census_Tracts_PercFamiliesBelowPovertyline_", year, ".png"),
    plot = map,
    width = 8,
    height = 6
  )
 cat("Map for year", year, "saved as LA_Census_Tracts_PercFamiliesBelowPovertyline_", year, ".png\n", sep = "")
}
combined_all_year_PercFamiliesBelowPovertyline <- bind_rows(all_year_PercFamiliesBelowPovertyline)
combined_all_year_PercFamiliesBelowPovertyline <- combined_all_year_PercFamiliesBelowPovertyline %>% st_drop_geometry()

write.csv(combined_all_year_PercFamiliesBelowPovertyline, "../Data/Demographic_Nov16/all_year_PercFamiliesBelowPovertyline.csv", row.names = FALSE)
print(combined_all_year_PercFamiliesBelowPovertyline)

yearly_PercFamiliesBelowPovertyline_avg <- combined_all_year_PercFamiliesBelowPovertyline %>%
  group_by(year) %>%
  summarize(avg_PercFamiliesBelowPovertyline_avg = mean(PercFamiliesBelowPovertyline, na.rm = TRUE))

tract_lines <- ggplot() +
  geom_line(data = combined_all_year_PercFamiliesBelowPovertyline, aes(x = year, y = PercFamiliesBelowPovertyline, group = GEOID),
            alpha = 0.1, color = "blue") +
  geom_line(data = yearly_PercFamiliesBelowPovertyline_avg, aes(x = year, y = avg_PercFamiliesBelowPovertyline_avg),
            color = "red", linewidth = 1, linetype = "dashed") +
  labs(
    title = "Change in Percentage of Families Below Poverty Line (2010-2019)",
    x = "Year",
    y = "Percentage of Families Below Poverty Line"
  ) +
  scale_y_continuous(limits = c(0, 100)) +
  #scale_x_continuous(
  #  breaks = 2010:2019,  
  #  labels = 2010:2019  
  #) +
  theme_minimal()
print(tract_lines)

```

```{r}
# create database
# Load all CSV files
unemployment <- read.csv("../Data/Demographic_Nov16/all_year_unemployment.csv")
race_data <- read.csv("../Data/Demographic_Nov16/all_year_race.csv")
pop_gender_race <- read.csv("../Data/Demographic_Nov16/all_year_pop_gender_race_maleRatio.csv")
income <- read.csv("../Data/Demographic_Nov16/all_year_income.csv")
povertyline <- read.csv("../Data/Demographic_Nov16/all_year_PercFamiliesBelowPovertyline.csv")
housingUnits <- read.csv("../Data/Demographic_Nov16/all_year_HousingUnit.csv")
MYB <- read.csv("../Data/Demographic_Nov16/all_year_MYB.csv")
YB <- read.csv("../Data/Demographic_Nov16/year2019_YearBuilt.csv")


data_frames <- list(pop_gender_race, race_data, unemployment, income, povertyline, housingUnits)

merged_data <- Reduce(function(x, y) full_join(x, y, by = c("GEOID", "year")), data_frames)
final_data <- full_join(merged_data, YB, by = "GEOID")
str(final_data)
# Save the merged data to a new CSV file
write.csv(final_data, "../Data/Demographic_Nov16/merged_data.csv", row.names = FALSE)

message("Data merged successfully and saved to 'merged_data.csv'")

df <- read.csv("../Data/Demographic_Nov16/merged_data.csv")
yearly_geoids <- df %>%
  group_by(year) %>%
  summarise(unique_geoid_count = n_distinct(GEOID))
print(yearly_geoids)
```